### ISSUE TITLE
fix(ingestion): W5 capture tests fail on docker lane — main red, python-ci-gate blocks merges (#2104)

### ISSUE THREAD

**Issue by daniel-ospina** [daniel-ospina/tortoise#2258]
## Main-red: W5 capture tests fail on the docker lane — python-ci-gate blocks all merges since ~14:19Z

**Blocker:** every PR merge-ref run since main tip `d24ec90c` fails the same three W5 (#2104) session-capture tests on the DOCKER lane. `python-ci-gate` (required check) aggregates the matrix → nothing has merged since #2244 (2026-09-04T14:19Z).

**Failing tests (identical node ids on main's own run 33883059708 at d24ec90c and on PR merge-refs):**
- `tests/test_hosted_api.py::TestSessionCaptureWriteVerb::test_capture_enrichment_failure_never_500s_committed_capture` (test-slow (a)) — `assert 'ok' == 'partial'`
- `tests/test_capture_session.py::test_session_capture_tool_fresh_team_captures` (test (a)) — `assert "error" not in result` fails; log carries `AttributeError: 'types.SimpleNamespace' object has no attribute 'headers'`
- `tests/test_capture_session.py::test_session_capture_tool_registered_and_invokeable` (test (a)) — same

**Repro (local, docker lane, merged tree):** `TORTOISE_DB_URI='docker://:falkordb@localhost:6379/tortoise_test_matrix' uv run pytest tests/test_hosted_api.py::TestSessionCaptureWriteVerb::test_capture_enrichment_failure_never_500s_committed_capture tests/test_capture_session.py -q` → 3 failed. (The two test_capture_session.py tests passed pre-W5-merge at 448eaf78 and fail post-merge — the W5 capture-path changes are the delta.)

**Root-cause notes (observed, not confirmed by owner):**
1. `test_capture_enrichment_failure_never_500s_committed_capture` monkeypatches the EMBEDDED redislite `Graph.query` to raise on the enrichment read — under the docker/server lane the enrichment query does not go through that handle class, so the boom never fires and the verb reports `ok` instead of the expected `partial`. Lane-dependent test patch.
2. The other two surface `AttributeError: 'types.SimpleNamespace' object has no attribute 'headers'` from the capture audit/provenance write path (hosted_api.py ~_capture_session_impl) on the docker lane.

**Files in the regression window:** W5 merge #2247 (+ review rounds ed489d96/711e12f7/afa08618) → tortoise/write_verb.py, hosted_api.py `_capture_session_impl`, tests/test_capture_session.py, tests/test_hosted_api.py.

**O/I/T:** O: python-ci-gate green again on main. I: the 3 tests pass on the docker lane; merges resume. T: the W5 capture team (#2104).

**Comment by daniel-ospina** [comment]
Additional rotating failures observed on PR merge-ref runs while main is red (all reproduce/rotate across legs; none in #2230's key-management surface — mint path untouched, tests pass in isolation locally):

- `tests/test_commit_supersession_parity.py::test_hosted_section6b_arm_alone_produces_the_fold` / `test_parity_helper_vs_hosted_section6b_identical_end_state` — `docker-lane redirect must isolate this arm on a test_* server graph … got both on 'tortoise'`
- `tests/test_hosted_api.py::TestBodySweepCaps::test_create_api_key_valid_body_still_mints` — `ControlPlaneError: Team 'team-001' not found` (passes in isolation)
- test-slow (a) also hit the 75m watchdog once.

Pattern: the python matrix legs are flaky across graph-isolation / control-plane-seed / capture-lane surfaces since the W5 (#2104) + C5 (#2241) merges; python-ci-gate (required) blocks every PR merge. Main python-ci history: 7fbd1baf fail, b9d3471c fail, d24ec90c fail, 8ec4afc2 (in progress).
